name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for raising this issue.The Repo maintainers will try to answer back asap.We are thankful for your patience!'
        pr-message: 'Thanks for raising this Pull Request.The Repo maintainers will check back asap!'
